// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfzI2lcb9Qq5rGxEYztFKIvufmikfJBbk',
    appId: '1:793924619975:web:0fbcd535552513831b78e2',
    messagingSenderId: '793924619975',
    projectId: 'madproject-c3aec',
    authDomain: 'madproject-c3aec.firebaseapp.com',
    storageBucket: 'madproject-c3aec.appspot.com',
    measurementId: 'G-8NDEGP1S3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwnt2TVSKr-aslfm0wTqgjmm4u53Ydav0',
    appId: '1:793924619975:android:d71b586f9b143d641b78e2',
    messagingSenderId: '793924619975',
    projectId: 'madproject-c3aec',
    storageBucket: 'madproject-c3aec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEycH7m2u0Wy_7RH9VQ7PspcBqF11eW7k',
    appId: '1:793924619975:ios:2fb122d2607a1b681b78e2',
    messagingSenderId: '793924619975',
    projectId: 'madproject-c3aec',
    storageBucket: 'madproject-c3aec.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEycH7m2u0Wy_7RH9VQ7PspcBqF11eW7k',
    appId: '1:793924619975:ios:2fb122d2607a1b681b78e2',
    messagingSenderId: '793924619975',
    projectId: 'madproject-c3aec',
    storageBucket: 'madproject-c3aec.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfzI2lcb9Qq5rGxEYztFKIvufmikfJBbk',
    appId: '1:793924619975:web:bb8c532a4f34669c1b78e2',
    messagingSenderId: '793924619975',
    projectId: 'madproject-c3aec',
    authDomain: 'madproject-c3aec.firebaseapp.com',
    storageBucket: 'madproject-c3aec.appspot.com',
    measurementId: 'G-97M4TYXHX1',
  );
}
